### ISSUE TITLE
Dialog "Do you wish to save the project before opening a new one?" opens even when the project was saved before through "Save Project" button.

### ISSUE THREAD

**Issue by Mikrischu** [einDamian/discrete-choice#32]
<img width="532" alt="Bildschirmfoto 2023-07-20 um 13 16 10" src="https://github.com/einDamian/discrete-choice/assets/133114285/a4aca5cb-003f-4170-aca4-25d5214a3b61">

**Comment by alice221927** [comment]
yes. I am aware of it. Do you have any idea how to check if a project has been saved lately?

**Comment by alice221927** [comment]
Will the project get automatically saved then?
imagine this scenario: The user saves the project immediately after creating it, but after 10 minutes he decides to open a new one. The path is obviously not  a None anymore, but the saved state is not most recent one.

**Comment by alice221927** [comment]
If you insist on checking for (path is None), I can do it no problem. I honestly still believe this is not a good solution. I'd rather have this warning window appearing every time instead of losing the data because of forgetting to save the prev. project. 
Another idea: maybe we can something like a time stamp for the project and i can check if the project has been saved in the last 30 seconds or something?

**Comment by alice221927** [comment]
This issue has been fixed :)
